### PR TITLE
feat(STONEINTG-605) updated clamav Dockerfile to ubi9

### PR DESCRIPTION
**Pull request by chipspeak**
Tested via manual triggering of workflow within fork. The specific workflow can be found [here](https://github.com/konflux-ci/konflux-test/blob/main/.github/workflows/clam-db.yaml)

### CODE REVIEW

**Comment by Josh-Everett** [comment]
would recommend changing the title to follow something akin to `feat(STONEINTG-605): updated clamav Dockerfile ...` for easier issue tracking otherwise LGTM

**Review by dheerajodha — APPROVED** [review]
I think it'd be worth mentioning (in the PR description) how this change was tested and attaching any useful links, for the reviewers.

Either way, LGTM! Thanks for the PR!

**Comment by dirgim** [comment]
@chipspeak I'd probably go even simpler for the commit title, but make it more obvious which version of ubi is now used, to make it simpler when scrolling through commits in the future.
Something like this:
```
feat(STONEINTG-605) chore: updated clamav Dockerfile to ubi9
```

**Comment by chipspeak** [comment]
> @chipspeak I'd probably go even simpler for the commit title, but make it more obvious which version of ubi is now used, to make it simpler when scrolling through commits in the future. Something like this:
> 
> ```
> feat(STONEINTG-605) chore: updated clamav Dockerfile to ubi9
> ```

Done!

**Review by jsztuka — APPROVED** [review]
lgtm

**Review by dirgim — APPROVED** [review]
LGTM

**Pull request merged**
