### PR TITLE
feat(CVP-4332): Install umoci to konflux-test image

### PR DESCRIPTION
**Pull request by yashvardhannanavati**
Required for a new Konflux task:  FIPS static check

CVP-4332

### CODE REVIEW

**Review by jsztuka — APPROVED** [review]
lgtm

**Comment by yashvardhannanavati** [comment]
@jsztuka @dirgim Could you please help trigger the konflux pipeline?

**Comment by yashvardhannanavati** [comment]
@dirgim looks like the test wasn't triggered :(

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by dirgim** [comment]
@yashvardhannanavati can you try rebasing on latest main? The Konflux test CI shouldn't be required anyways.

**Comment by yashvardhannanavati** [comment]
@dirgim rebased it :)

**Pull request merged**
